<a href="https://colab.research.google.com/github/OrangeBird295/ReviewPython/blob/main/Review_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Create array 1 dimension

In [1]:
import numpy as np
arr1 = np.array(1)
arr1

array(1)

In [34]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

Check dimension of np.array

In [5]:
a1.ndim

1

Create list to defind np.array

In [6]:
li = [1, 2, 3, 4, 5]
b1 = np.array(li)
b1

# or

tu = (1, 2, 3, 4)
c1 = np.array(tu)
c1

array([1, 2, 3, 4])

# Create array 2 dimension

In [10]:
a2 = np.array([[1, 2, 3],[4, 5, 6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a2.ndim

2

In [12]:
li2 = [[1, 2, 3],[4 ,5 ,6],[7, 8, 9]]
c2 = np.array(li2)
c2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
tu2 = ((1, 2, 3),(4 , 5, 6),(7 ,8, 9))
b2 = np.array(tu2)
b2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Create array 3 dimension

In [8]:
a3 = np.array([[[1, 2, 3],[4, 5 ,6]]])
a3

array([[[1, 2, 3],
        [4, 5, 6]]])

In [9]:
a3.ndim

3

# Access value in array 1 dimension

In [15]:
a4 = np.array([1, 2, 3 ,4])
a4

array([1, 2, 3, 4])

In [16]:
a4[2]

3

# Access value in array 2 dimension

In [17]:
a5 = np.array([[1 ,2 ,3],[4, 5, 6]])
a5

array([[1, 2, 3],
       [4, 5, 6]])

array[row][column]

In [18]:
a5[1][2]

6

# Access value in array 3 dimension

In [19]:
a6 = np.array([[[1, 2, 3],[4, 5, 6]]])
a6

array([[[1, 2, 3],
        [4, 5, 6]]])

In [20]:
a6.ndim

3

array[dept][row][column]

In [23]:
a6[0][1][1]

5

In [26]:
b6 = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])
b6

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [28]:
b6[1][1][1]

11

# Data type

In [29]:
a7 = np.array([1, 2 , 3, 4], dtype="int")
a7

array([1, 2, 3, 4])

In [30]:
a7.dtype

dtype('int64')

In [31]:
b7 = np.array([1, 2, 3, 4], dtype="float")
b7

array([1., 2., 3., 4.])

In [32]:
b7.dtype

dtype('float64')

# Metrix

## Zero Metrix สมาชิกทุกตัวเป็น 0

In [36]:
a8 = np.zeros(5)
a8

array([0., 0., 0., 0., 0.])

In [39]:
np.zeros(6, dtype="int")

array([0, 0, 0, 0, 0, 0])

In [41]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [46]:
 np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Ones Metrix สมาชิกทุกตัวเป็น 1

In [47]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [48]:
np.ones(10, dtype="int")

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [52]:
a9 = np.ones([2, 3], dtype="int")  
a9

array([[1, 1, 1],
       [1, 1, 1]])

## Full Metrix สมาชิกทุกตัวเป็นตามที่กำหนด

In [53]:
np.full(10, 7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [56]:
a10 = np.full([3, 4], 2)
a10

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

## Create Empty Array by F(x)->empty  สร้าง array ปล่าวๆ และค่าทุกตัวใน Array จะถูกสุ่มขึ้นมา  
่ส่วนใหญ่ใช้ในการกำหนดขนาด เพราะสร้างเร็วกว่าตัวอื่น

In [59]:
a11 = np.empty([3, 4])
a11

array([[1.e-323, 1.e-323, 1.e-323, 1.e-323],
       [1.e-323, 1.e-323, 1.e-323, 1.e-323],
       [1.e-323, 1.e-323, 1.e-323, 1.e-323]])

## Identity Metrix สมาชิกเส้นทแยงมุมเป็น 1 ที่เหลือเป็น 0 (ขนาดต้องเท่ากัน) == F(x) eye(ขนาดไม่ต้องเท่ากัน)

In [63]:
a12 = np.identity(4, dtype="int")
a12

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

f(x) eye

In [64]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [68]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [70]:
np.eye(5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [71]:
np.eye(5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

## Linspace
ระบุจำนวนช่วงของตัวเลขได้ และระบุจำนวนสมาชิก

np.linspace(start, stop, number)

เหมาะสำหรับการ port graph

In [79]:
a13 = np.linspace(1, 10) 
a13

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [80]:
np.linspace(1, 5, 4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [84]:
# ไม่เอาตัวสุดท้าย 
np.linspace(1, 5, endpoint=False)

array([1.  , 1.08, 1.16, 1.24, 1.32, 1.4 , 1.48, 1.56, 1.64, 1.72, 1.8 ,
       1.88, 1.96, 2.04, 2.12, 2.2 , 2.28, 2.36, 2.44, 2.52, 2.6 , 2.68,
       2.76, 2.84, 2.92, 3.  , 3.08, 3.16, 3.24, 3.32, 3.4 , 3.48, 3.56,
       3.64, 3.72, 3.8 , 3.88, 3.96, 4.04, 4.12, 4.2 , 4.28, 4.36, 4.44,
       4.52, 4.6 , 4.68, 4.76, 4.84, 4.92])

## Arange
np.arange(start, stop, step)

In [86]:
a14 = np.arange(10)
a14

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
np.arange(10.0)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [91]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [92]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

## Random
สุ่มค่าใน Array ช่วง 0 ถึงก่อน 1

In [93]:
a15 = np.random.random((2, 2))
a15

array([[0.5119971 , 0.83983527],
       [0.05164307, 0.23679458]])